version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379"

  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./chebaba/public:/wwwroot
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:5.6-fpm
    volumes:
      - ./chebaba/public:/wwwroot
